/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PharmaceuticalList.h
 *
 * 
 */

#ifndef IO_PHARMATRACE_API_SCIN_PUBLIC_MODEL_PharmaceuticalList_H_
#define IO_PHARMATRACE_API_SCIN_PUBLIC_MODEL_PharmaceuticalList_H_


#include "../ModelBase.h"

#include "Pharmaceutical.h"
#include <vector>

namespace io {
namespace pharmatrace {
namespace api {
namespace scin {
namespace public {
namespace model {

/// <summary>
/// 
/// </summary>
class  PharmaceuticalList
    : public ModelBase
{
public:
    PharmaceuticalList();
    virtual ~PharmaceuticalList();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PharmaceuticalList members

    /// <summary>
    /// Contains the list of products
    /// </summary>
    std::vector<std::shared_ptr<Pharmaceutical>>& getProducts();
    bool productsIsSet() const;
    void unsetProducts();

    void setProducts(const std::vector<std::shared_ptr<Pharmaceutical>>& value);


protected:
    std::vector<std::shared_ptr<Pharmaceutical>> m_Products;
    bool m_ProductsIsSet;
};

}
}
}
}
}
}

#endif /* IO_PHARMATRACE_API_SCIN_PUBLIC_MODEL_PharmaceuticalList_H_ */
